name = "SPICE"
uuid = "5bab7191-041a-5c2e-a744-024b9c3a5062"
version = "0.2.3"

[deps]
CSPICE_jll = "07f52509-e9d9-513c-a20d-3b911885bf96"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"

[compat]
julia = "1.6"
CSPICE_jll = "67"

[targets]
test = ["LinearAlgebra", "Test", "Random", "RemoteFiles"]
